src/administrator/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from administrator.views import QuranRosterClasses, QuranRosterClassList, IslamicStudiesRosterClasses, IslamicStudiesRosterClassList, QuranPostsList,IslamicStudiesPostsList,QuranClassPostListView,IslamicStudiesClassPostListView,QuranClassExamScores,QuranClassesExamList,IslamicStudiesClassExamScores, IslamicStudiesClassesExamList, QuranClassWeekAttendance, QuranClassWeekAttendanceUpdate, QuranClassesAttendanceList, QuranClassWeeksList, IslamicStudiesClassWeekAttendance, IslamicStudiesClassWeekAttendanceUpdate, IslamicStudiesClassesAttendanceList, IslamicStudiesClassWeeksList, IslamicStudiesExamScoreAdd, QuranExamScoreAdd,FullStudentList,FullTeacherList

urlpatterns = [
    url(r'^all-students/$', FullStudentList.as_view(),name='all_students'),
    url(r'^all-teachers/$', FullTeacherList.as_view(),name='all_teachers'),
    url(r'^quran-class-rosters/$', QuranRosterClasses.as_view(),name='qrosters'),
    url(r'^quran-class-rosters/$', QuranRosterClasses.as_view(),name='qrosters'),
    url(r'^quran-class-rosters/(?P<level>([1-9]|10))/$', QuranRosterClassList.as_view(),name='quranstudentlist'),
    url(r'^islamic-studies-class-rosters/$', IslamicStudiesRosterClasses.as_view(),name='isrosters'),
    url(r'^islamic-studies-class-rosters/(?P<level>([1-9]|10))/$', IslamicStudiesRosterClassList.as_view(),name='islamicstudiesstudentlist'),
    url(r'^quran-class-posts/$', QuranPostsList.as_view(),name='quran_posts_list'),
    url(r'^islamic-studies-class-posts/$', IslamicStudiesPostsList.as_view(),name='islamic_studies_posts_list'),
    url(r'^quran-class-posts/(?P<level>([1-9]|10))/$', QuranClassPostListView.as_view(),name='quranclassposts'),
    url(r'^islamic-studies-class-posts/(?P<level>([1-9]|10))/$', IslamicStudiesClassPostListView.as_view(),name='islamicstudiesclassposts'),
    url(r'^quran-class-exams/$', QuranClassesExamList.as_view(),name='quran_classes_exams'),
    url(r'^quran-class-exams/(?P<level>([1-9]|10))/$', QuranClassExamScores.as_view(),name='quran_class_exam_scores'),
    url(r'^quran-class-exams/(?P<level>([1-9]|10))/add/(?P<student>[\w\.-]+)/$', QuranExamScoreAdd.as_view(),name='quran_exam_score_add'),
    url(r'^islamic-studies-class-exams/$', IslamicStudiesClassesExamList.as_view(),name='islamic_studies_classes_exams'),
    url(r'^islamic-studies-class-exams/(?P<level>([1-9]|10))/$', IslamicStudiesClassExamScores.as_view(),name='islamic_studies_class_exam_scores'),
    url(r'^islamic-studies-class-exams/(?P<level>([1-9]|10))/add/(?P<student>[\w\.-]+)/$', IslamicStudiesExamScoreAdd.as_view(),name='islamic_studies_exam_score_add'),
    url(r'^quran-class-attendance/$', QuranClassesAttendanceList.as_view(),name='quran_attendance_list'),
    url(r'^quran-class-attendance/(?P<level>([1-9]|10))/$', QuranClassWeeksList.as_view(),name='quran_weeks_list'),
    url(r'^quran-class-attendance/(?P<level>([1-9]|10))/(?P<week>\d+)/$', QuranClassWeekAttendance.as_view(),name='quran_week_attendance'),
    url(r'^quran-class-attendance/(?P<level>([1-9]|10))/(?P<week>\d+)/(?P<student>[\w\.-]+)/(?P<pk>\d+)/$', QuranClassWeekAttendanceUpdate.as_view(),name='quran_week_attendance_update'),
    url(r'^islamic-studies-class-attendance/$', IslamicStudiesClassesAttendanceList.as_view(),name='islamic_studies_attendance_list'),
    url(r'^islamic-studies-class-attendance/(?P<level>([1-9]|10))/$', IslamicStudiesClassWeeksList.as_view(),name='islamic_studies_weeks_list'),
    url(r'^islamic-studies-class-attendance/(?P<level>([1-9]|10))/(?P<week>\d+)/$', IslamicStudiesClassWeekAttendance.as_view(),name='islamic_studies_week_attendance'),
    url(r'^islamic-studies-class-attendance/(?P<level>([1-9]|10))/(?P<week>\d+)/(?P<student>[\w\.-]+)/(?P<pk>\d+)/$', IslamicStudiesClassWeekAttendanceUpdate.as_view(),name='islamic_studies_week_attendance_update'),




]

src/arkportal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from profiles.views import DashboardView, QuranClassListView, ISClassListView, QuranPostListView, QuranPostDetailView, QuranCreatePostView, add_comment_to_quran_post, IslamicStudiesPostListView, IslamicStudiesPostDetailView, IslamicStudiesCreatePostView, add_comment_to_islamic_studies_post, QuranTeacherStudentList, QuranExamScoreAdd, StudentDetail, TeacherDetail, QuranExamScoreUpdate, IslamicStudiesExamScoreAdd, IslamicStudiesTeacherStudentList, IslamicStudiesExamScoreUpdate,QuranSchoolWeeksView, QuranAttendanceList, QuranAttendanceUpdate, QuranAttendanceStudentView, IslamicStudiesSchoolWeeksView, IslamicStudiesAttendanceList, IslamicStudiesAttendanceUpdate, IslamicStudiesAttendanceStudentView, QuranExamStudentView, IslamicStudiesExamStudentView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(template_name='registration/login.html'),name='login'),
    url(r'^logout/$', LogoutView.as_view(),name='logout'),
    url(r'^dashboard/$', DashboardView.as_view(),name='dashboard'),
    url(r'^administrator/', include('administrator.urls',namespace='administrator')),
    url(r'^students/(?P<username>[\w\.-]+)/$', StudentDetail.as_view(),name='student_detail'),
    url(r'^teachers/(?P<username>[\w\.-]+)/$', TeacherDetail.as_view(),name='teacher_detail'),
    url(r'^quran-class-roster/$', QuranClassListView.as_view(),name='qroster'),
    url(r'^islamic-studies-class-roster/$', ISClassListView.as_view(),name='isroster'),
    url(r'^quran-class-students/$', QuranTeacherStudentList.as_view(),name='quran_student_list'),
    url(r'^quran-class-student/exam-scores-add/(?P<student>[\w\.-]+)/$', QuranExamScoreAdd.as_view(),name='quran_score_add'),
    url(r'^quran-class-student/exam-scores-add/(?P<student>[\w\.-]+)/(?P<pk>\d+)/$', QuranExamScoreUpdate.as_view(),name='quran_score_update'),
    url(r'^islamic-studies-class-students/$', IslamicStudiesTeacherStudentList.as_view(),name='islamic_studies_student_list'),
    url(r'^islamic-studies-class-student/exam-scores-add/(?P<student>[\w\.-]+)/$', IslamicStudiesExamScoreAdd.as_view(),name='islamic_studies_score_add'),
    url(r'^islamic-studies-class-student/exam-scores-add/(?P<student>[\w\.-]+)/(?P<pk>\d+)/$', IslamicStudiesExamScoreUpdate.as_view(),name='islamic_studies_score_update'),
    url(r'^quran-class-posts/$', QuranPostListView.as_view(),name='quran_post_list'),
    url(r'^quran-class-posts/create/$', QuranCreatePostView.as_view(),name='quran_post_new'),
    url(r'^quran-class-posts/(?P<pk>\d+)/$', QuranPostDetailView.as_view(),name='quran_post_detail'),
    url(r'^quran-class-posts/(?P<pk>\d+)/comment/$', add_comment_to_quran_post,name='comment_quran_post'),
    url(r'^islamic-studies-class-posts/$', IslamicStudiesPostListView.as_view(),name='islamic_studies_post_list'),
    url(r'^islamic-studies-class-posts/create/$', IslamicStudiesCreatePostView.as_view(),name='islamic_studies_post_new'),
    url(r'^islamic-studies-class-posts/(?P<pk>\d+)/$', IslamicStudiesPostDetailView.as_view(),name='islamic_studies_post_detail'),
    url(r'^islamic-studies-class-posts/(?P<pk>\d+)/comment/$', add_comment_to_islamic_studies_post,name='comment_islamic_studies_post'),
    url(r'^quran-class-students/attendance/$', QuranSchoolWeeksView.as_view(),name='quran_school_weeks'),
    url(r'^quran-class-students/attendance/(?P<pk>\d+)/student-list/$', QuranAttendanceList.as_view(),name='quran_attendance_list'),
    url(r'^quran-class-students/attendance/student-list/(?P<student>[\w\.-]+)/(?P<pk>\d+)$', QuranAttendanceUpdate.as_view(),name='quran_attendance_update'),
    url(r'^quran-class/attendance/$', QuranAttendanceStudentView.as_view(),name='student_quran_attendance'),
    url(r'^quran-class/exam-results/$', QuranExamStudentView.as_view(),name='student_quran_exams'),
    url(r'^islamic-studies-class-students/attendance/$', IslamicStudiesSchoolWeeksView.as_view(),name='islamic_studies_school_weeks'),
    url(r'^islamic-studies-class-students/attendance/(?P<pk>\d+)/student-list/$', IslamicStudiesAttendanceList.as_view(),name='islamic_studies_attendance_list'),
    url(r'^islamic-studies-class-students/attendance/student-list/(?P<student>[\w\.-]+)/(?P<pk>\d+)$', IslamicStudiesAttendanceUpdate.as_view(),name='islamic_studies_attendance_update'),
    url(r'^islamic-studies-class/attendance/$', IslamicStudiesAttendanceStudentView.as_view(),name='student_islamic_studies_attendance'),
    url(r'^islamic-studies-class/exam-results/$', IslamicStudiesExamStudentView.as_view(),name='student_islamic_studies_exams'),

]

src/templates/dashboardbase.html
<!DOCTYPE html>
{% load static %}
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>The Ark Institute Student Portal | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> 

 <!-- Font Awesome -->
 <script src="https://use.fontawesome.com/d2f68dc124.js"></script>

  <!-- Ionicons -->

   {# MEDIUM STYLE EDITOR#}
<script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "AdminLTE.min.copy.css" %}">

  <link rel="stylesheet" href="{% static "skin-red-light.min.copy.css" %}">


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

  <link rel="stylesheet" type="text/css" href="{% static "styling.css" %}">
  
</head>

<body class="hold-transition skin-red-light sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    {% include "topnav.html" %}

  </header>

  <!-- SIDEBAR INCLUDES-->
  {% if request.user.is_staff %}

        {% include "administrator/adminmainnav.html" %}


  {% else %}
    
      {% include "mainnav.html" %}

  {% endif %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      {% block title %}
        <h1>
        {{request.user.first_name}}'s Dashboard
        <small>{{request.user.profile.role}}</small>
        </h1>
      {% endblock title %}
       
      <!--
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Here</li>
      </ol>
      -->
    </section>

    <!-- Main content -->
    <section class="content container-fluid">


        {% block maincontent %}
          
        {% endblock  %}

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      'Seek knowledge from cradle to grave' - The Holy Prophet
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2017 <a href="#">The Ark Institute</a>.</strong> All rights reserved.
  </footer>

</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script
  src="https://code.jquery.com/jquery-3.0.0.min.js"
  integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0="
  crossorigin="anonymous"></script>

  <!-- Bootstrap 3.3.7 -->
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- AdminLTE App -->
<script src="{% static "adminlte.min.copy.js" %}"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>

src/templates/error.html
{% extends "dashboardbase.html" %}

{% block title %}
	
{% endblock %}

{% block maincontent %}
	
	<h4>Sorry you cannot view this page :( </h4>

{% endblock %}

src/templates/islamic_studies_comment_form.html
{% extends "dashboardbase.html" %}

{% load bootstrap3 %}

{% block title %}
	<div class="container-fluid">

	<div class="text-center">
		<h2>
			Write a Comment
		</h2>
	</div>

    <div class="pull-right">
        <a href="{% url 'islamic_studies_post_list' %}" class="btn btn-primary">Go back</a>
    </div>
 	</div>

        <div class="alert alert-danger alert-dismissible" style="margin-top: 10px;">

                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <i class="icon fa fa-warning"></i>
                Once you post a comment, you will not be able to delete it. Double click and highlight your comment text if you wish to style it.
        </div>

{% endblock  %}

{% block maincontent %}

<div class="well posts">

    <form method="POST" class="post-form">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-danger">Comment</button>
    </form>


</div>	 


    <script>var editor = new MediumEditor('.editable');</script>

{% endblock  %}

src/templates/islamic_studies_post_form.html
{% extends "dashboardbase.html" %}
{% load static %}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static "styling.css" %}">
</head>

{% block title %}
	<div class="container-fluid">

	<div class="text-center">
		<h2>
			Create a Post
		</h2>
	</div>

    <div class="pull-right">
        <a href="{% url 'islamic_studies_post_list' %}" class="btn btn-primary">Go back</a>
    </div>
 	</div>

    <div class="alert alert-danger alert-dismissible" style="margin-top: 10px;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <i class="icon fa fa-warning"></i>
                Once you create a post, you will not be able to delete it. Double click and highlight your message text if you wish to style it.
    </div>


{% endblock  %}

<body>

{% block maincontent %}




<div class="well posts">
    <form method="POST" class="post-form" enctype="multipart/form-data">
  
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-danger">Post</button>
  
  </form>
</div>	 


    <script>var editor = new MediumEditor('.editable');</script>

{% endblock  %}

</body>
</html>

src/templates/islamic_studies_post_list.html
{% extends "dashboardbase.html" %}

{% load bootstrap3 %}

{% block title %}
    <div class="container-fluid">
    <div class="text-center">
	<h2>
		Islamic Studies {{request.user.profile.islamic_studies_class}}: Class Posts
	</h2>
    </div>
        <div class="pull-right">
            <a href="{% url 'islamic_studies_post_new' %}" class="btn btn-primary">Create Post</a>
        </div>
    </div>
{% endblock  %}

{% block maincontent %}
	 
    {% for post in object_list %}
        <div class="well posts">
            <h1><a href="{% url 'islamic_studies_post_detail' pk=post.pk %}" style="color:#dd4b39;">{{ post.title }}</a></h1>
            <p><b>Posted by:</b> {{post.author.first_name}} {{post.author.last_name}}</p>
            <p><b>Posted on:</b> {{ post.posted_date|date:"D M Y"}}</p>
            <hr>
            <h5>{{post.message|safe}}</h5>
            <hr>
            <a href="{% url 'islamic_studies_post_detail' pk=post.pk %}">Comments: {{ post.islamic_studies_comments.count }}</a>
            <a href="{% url 'comment_islamic_studies_post' pk=post.pk %}" style="margin-left: 5px;" class="btn btn-danger pull-right">Comment</a>
            <a href="{% url 'islamic_studies_post_detail' pk=post.pk %}" class="btn btn-success pull-right">View</a>
        </div>

    {% empty %}
    <p>There are no posts to show.</p>

    {% endfor %}



{% endblock  %}

src/templates/islamic_studies_school_weeks.html
{% extends "dashboardbase.html" %}

{% block title %}
<div class="text-center">
    <h2>
    Islamic Studies {{user.profile.islamic_studies_class}} Attendance
  </h2>
</div>

{% endblock  %}

{% block maincontent %}
    <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
                {% for teacher in teachers  %}
                  <b class="box-title">Teacher:</b> {{teacher.first_name}} {{teacher.last_name}}: {{teacher.email}}<br>
                {% endfor %}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Week</th>
                  <th>Date</th>
                  <th>Student Attendance</th>            
                </tr>
                </thead>
                <tbody>

                {% for week in object_list  %}
                  <tr>
                    <td>{{week.week_number}}</td>
                    <td>{{week.date}}</td>
                    {% if request.user.profile.role == 'Teacher' %}        
                      <td><a href="{% url 'islamic_studies_attendance_list' pk=week.pk %}" class="btn btn-primary">Enter</a></td>
                    {% endif %}
                  </tr>
                  
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock  %}

src/templates/isroster.html
{% extends "dashboardbase.html" %}

{% block title %}
<div class="text-center">
    <h2>
    Islamic Studies {{user.profile.islamic_studies_class}}
  </h2>
</div>

{% endblock  %}

{% block maincontent %}
	  <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
                {% for teacher in teachers  %}
                  <b>Teacher:</b> {{teacher.first_name}} {{teacher.last_name}} ({{teacher.email}})<br>
                {% endfor %}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email Adress</th>            
                  <th>Quran Class</th>   
                  {% if request.user.profile.role == 'Teacher' %}
                  <th>Student Profile</th>
                  {% endif %}
                </tr>
                </thead>
                <tbody>

                {% for user in object_list  %}
                	<tr>
                		<td>{{user.first_name}}</td>
                		<td>{{user.last_name}}</td>
                	    <td>{{user.email}}</td>                
                  		<td>{{user.profile.quran_class}}</td>
                      {% if request.user.profile.role == 'Teacher' %}        
                        <td><a href="{% url 'student_detail' username=user.username %}" class="btn btn-primary">View</a></td>
                      {% endif %}
                	</tr>
                	
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock  %}

src/templates/quran_comment_form.html
{% extends "dashboardbase.html" %}

{% load bootstrap3 %}

{% block title %}
	<div class="container-fluid">

	<div class="text-center">
		<h2>
			Write a Comment
		</h2>
	</div>

    <div class="pull-right">
        <a href="{% url 'quran_post_list' %}" class="btn btn-primary">Go back</a>
    </div>
 	</div>

        <div class="alert alert-danger alert-dismissible" style="margin-top: 10px;">

                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <i class="icon fa fa-warning"></i>
                Once you post a comment, you will not be able to delete it. Double click and highlight your comment text if you wish to style it.
        </div>

{% endblock  %}

{% block maincontent %}

<div class="well posts">

    <form method="POST" class="post-form">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-danger">Comment</button>
    </form>


</div>	 


    <script>var editor = new MediumEditor('.editable');</script>

{% endblock  %}

src/templates/quran_post_detail.html
{% extends 'dashboardbase.html' %}

{% block title %}
 <div class="container-fluid">
  <div class="text-center">
      <h2>
        Quran {{object.class_level}} Post
      </h2>
    </div>
      <div class="pull-right">
      {% if request.user.is_staff %}
        <a href="{% url 'administrator:quran_posts_list'%}" class="btn btn-primary">All Classes</a>
      {% else %}
        <a href="{% url 'quran_post_list' %}" class="btn btn-primary">All Posts</a>
      {% endif %}
      </div>
 </div>

{% endblock  %}

{% block maincontent %}

<div class="well posts">

        <h1 class='posttitle loader'>{{ object.title }}</h1>

        <hr>
        <p><b>Posted by:</b> {{object.author.first_name}} {{object.author.last_name}}</p>
        <p><b>Posted on:</b> {{ object.posted_date }} </p>
        {% if object.upload %}<p><b>Attachment:</b>
          <a href="{{object.upload.url}}">{{object.upload}}</a>
        {% endif %}
        </p>
        <hr>

        <p> {{object.message|safe|linebreaksbr }} </p>

      

</div>

{% if not request.user.is_staff %}
<a href="{% url 'comment_quran_post' pk=object.pk %}" class="btn btn-danger pull-right">Comment</a>
{% endif %}

<br>
<br>
<h2 style="text-align: center;">Comments</h2>

<hr>

  {% for comment in object.quran_comments.all %}

  
  <div class="col-sm-9 col-sm-offset-1 posts">

      <p><strong>{{ comment.author.first_name }} {{ comment.author.last_name }}</strong></p>
      <p>{{ comment.posted_date }}</p>
      <hr>
      <p>{{ comment.comment|safe|linebreaks }}</p>    

  </div>



  {% empty %}
    <p>No comments posted.</p>
   
  {% endfor %}


{% endblock %}

src/templates/quran_post_form.html
{% extends "dashboardbase.html" %}
{% load static %}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static "styling.css" %}">
</head>

{% block title %}
	<div class="container-fluid">

	<div class="text-center">
		<h2>
			Create a Post
		</h2>
	</div>

    <div class="pull-right">
        <a href="{% url 'quran_post_list' %}" class="btn btn-primary">Go back</a>
    </div>
 	</div>

    <div class="alert alert-danger alert-dismissible" style="margin-top: 10px;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <i class="icon fa fa-warning"></i>
                Once you create a post, you will not be able to delete it. Double click and highlight your message text if you wish to style it.
    </div>


{% endblock  %}

<body>

{% block maincontent %}




<div class="well posts">
    <form method="POST" class="post-form" enctype="multipart/form-data">
  
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-danger">Post</button>
  
  </form>
</div>	 


    <script>var editor = new MediumEditor('.editable');</script>

{% endblock  %}

</body>
</html>

src/templates/quran_school_weeks.html
{% extends "dashboardbase.html" %}

{% block title %}
<div class="text-center">
    <h2>
    Quran {{user.profile.quran_class}} Attendance
  </h2>
</div>

{% endblock  %}

{% block maincontent %}
    <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
                {% for teacher in teachers  %}
                  <b class="box-title">Teacher:</b> {{teacher.first_name}} {{teacher.last_name}}: {{teacher.email}}<br>
                {% endfor %}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Week</th>
                  <th>Date</th>
                  <th>Student Attendance</th>            
                </tr>
                </thead>
                <tbody>

                {% for week in object_list  %}
                  <tr>
                    <td>{{week.week_number}}</td>
                    <td>{{week.date}}</td>
                    {% if request.user.profile.role == 'Teacher' %}        
                      <td><a href="{% url 'quran_attendance_list' pk=week.pk %}" class="btn btn-primary">Enter</a></td>
                    {% endif %}
                  </tr>
                  
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock  %}