src/administrator/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from administrator.views import QuranRosterClasses, QuranRosterClassList, IslamicStudiesRosterClasses, IslamicStudiesRosterClassList, QuranPostsList,IslamicStudiesPostsList,QuranClassPostListView,IslamicStudiesClassPostListView,QuranClassExamScores,QuranClassesExamList,IslamicStudiesClassExamScores, IslamicStudiesClassesExamList, QuranClassWeekAttendance, QuranClassWeekAttendanceUpdate, QuranClassesAttendanceList, QuranClassWeeksList, IslamicStudiesClassWeekAttendance, IslamicStudiesClassWeekAttendanceUpdate, IslamicStudiesClassesAttendanceList, IslamicStudiesClassWeeksList, IslamicStudiesExamScoreAdd, QuranExamScoreAdd,FullStudentList,FullTeacherList

urlpatterns = [
    url(r'^all-students/$', FullStudentList.as_view(),name='all_students'),
    url(r'^all-teachers/$', FullTeacherList.as_view(),name='all_teachers'),
    url(r'^quran-class-rosters/$', QuranRosterClasses.as_view(),name='qrosters'),
    url(r'^quran-class-rosters/$', QuranRosterClasses.as_view(),name='qrosters'),
    url(r'^quran-class-rosters/(?P<level>([1-9]|10))/$', QuranRosterClassList.as_view(),name='quranstudentlist'),
    url(r'^islamic-studies-class-rosters/$', IslamicStudiesRosterClasses.as_view(),name='isrosters'),
    url(r'^islamic-studies-class-rosters/(?P<level>([1-9]|10))/$', IslamicStudiesRosterClassList.as_view(),name='islamicstudiesstudentlist'),
    url(r'^quran-class-posts/$', QuranPostsList.as_view(),name='quran_posts_list'),
    url(r'^islamic-studies-class-posts/$', IslamicStudiesPostsList.as_view(),name='islamic_studies_posts_list'),
    url(r'^quran-class-posts/(?P<level>([1-9]|10))/$', QuranClassPostListView.as_view(),name='quranclassposts'),
    url(r'^islamic-studies-class-posts/(?P<level>([1-9]|10))/$', IslamicStudiesClassPostListView.as_view(),name='islamicstudiesclassposts'),
    url(r'^quran-class-exams/$', QuranClassesExamList.as_view(),name='quran_classes_exams'),
    url(r'^quran-class-exams/(?P<level>([1-9]|10))/$', QuranClassExamScores.as_view(),name='quran_class_exam_scores'),
    url(r'^quran-class-exams/(?P<level>([1-9]|10))/add/(?P<student>[\w\.-]+)/$', QuranExamScoreAdd.as_view(),name='quran_exam_score_add'),
    url(r'^islamic-studies-class-exams/$', IslamicStudiesClassesExamList.as_view(),name='islamic_studies_classes_exams'),
    url(r'^islamic-studies-class-exams/(?P<level>([1-9]|10))/$', IslamicStudiesClassExamScores.as_view(),name='islamic_studies_class_exam_scores'),
    url(r'^islamic-studies-class-exams/(?P<level>([1-9]|10))/add/(?P<student>[\w\.-]+)/$', IslamicStudiesExamScoreAdd.as_view(),name='islamic_studies_exam_score_add'),
    url(r'^quran-class-attendance/$', QuranClassesAttendanceList.as_view(),name='quran_attendance_list'),
    url(r'^quran-class-attendance/(?P<level>([1-9]|10))/$', QuranClassWeeksList.as_view(),name='quran_weeks_list'),
    url(r'^quran-class-attendance/(?P<level>([1-9]|10))/(?P<week>\d+)/$', QuranClassWeekAttendance.as_view(),name='quran_week_attendance'),
    url(r'^quran-class-attendance/(?P<level>([1-9]|10))/(?P<week>\d+)/(?P<student>[\w\.-]+)/(?P<pk>\d+)/$', QuranClassWeekAttendanceUpdate.as_view(),name='quran_week_attendance_update'),
    url(r'^islamic-studies-class-attendance/$', IslamicStudiesClassesAttendanceList.as_view(),name='islamic_studies_attendance_list'),
    url(r'^islamic-studies-class-attendance/(?P<level>([1-9]|10))/$', IslamicStudiesClassWeeksList.as_view(),name='islamic_studies_weeks_list'),
    url(r'^islamic-studies-class-attendance/(?P<level>([1-9]|10))/(?P<week>\d+)/$', IslamicStudiesClassWeekAttendance.as_view(),name='islamic_studies_week_attendance'),
    url(r'^islamic-studies-class-attendance/(?P<level>([1-9]|10))/(?P<week>\d+)/(?P<student>[\w\.-]+)/(?P<pk>\d+)/$', IslamicStudiesClassWeekAttendanceUpdate.as_view(),name='islamic_studies_week_attendance_update'),




]

src/arkportal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from profiles.views import DashboardView, QuranClassListView, ISClassListView, QuranPostListView, QuranPostDetailView, QuranCreatePostView, add_comment_to_quran_post, IslamicStudiesPostListView, IslamicStudiesPostDetailView, IslamicStudiesCreatePostView, add_comment_to_islamic_studies_post, QuranTeacherStudentList, QuranExamScoreAdd, StudentDetail, TeacherDetail, QuranExamScoreUpdate, IslamicStudiesExamScoreAdd, IslamicStudiesTeacherStudentList, IslamicStudiesExamScoreUpdate,QuranSchoolWeeksView, QuranAttendanceList, QuranAttendanceUpdate, QuranAttendanceStudentView, IslamicStudiesSchoolWeeksView, IslamicStudiesAttendanceList, IslamicStudiesAttendanceUpdate, IslamicStudiesAttendanceStudentView, QuranExamStudentView, IslamicStudiesExamStudentView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(template_name='registration/login.html'),name='login'),
    url(r'^logout/$', LogoutView.as_view(),name='logout'),
    url(r'^dashboard/$', DashboardView.as_view(),name='dashboard'),
    url(r'^administrator/', include('administrator.urls',namespace='administrator')),
    url(r'^students/(?P<username>[\w\.-]+)/$', StudentDetail.as_view(),name='student_detail'),
    url(r'^teachers/(?P<username>[\w\.-]+)/$', TeacherDetail.as_view(),name='teacher_detail'),
    url(r'^quran-class-roster/$', QuranClassListView.as_view(),name='qroster'),
    url(r'^islamic-studies-class-roster/$', ISClassListView.as_view(),name='isroster'),
    url(r'^quran-class-students/$', QuranTeacherStudentList.as_view(),name='quran_student_list'),
    url(r'^quran-class-student/exam-scores-add/(?P<student>[\w\.-]+)/$', QuranExamScoreAdd.as_view(),name='quran_score_add'),
    url(r'^quran-class-student/exam-scores-add/(?P<student>[\w\.-]+)/(?P<pk>\d+)/$', QuranExamScoreUpdate.as_view(),name='quran_score_update'),
    url(r'^islamic-studies-class-students/$', IslamicStudiesTeacherStudentList.as_view(),name='islamic_studies_student_list'),
    url(r'^islamic-studies-class-student/exam-scores-add/(?P<student>[\w\.-]+)/$', IslamicStudiesExamScoreAdd.as_view(),name='islamic_studies_score_add'),
    url(r'^islamic-studies-class-student/exam-scores-add/(?P<student>[\w\.-]+)/(?P<pk>\d+)/$', IslamicStudiesExamScoreUpdate.as_view(),name='islamic_studies_score_update'),
    url(r'^quran-class-posts/$', QuranPostListView.as_view(),name='quran_post_list'),
    url(r'^quran-class-posts/create/$', QuranCreatePostView.as_view(),name='quran_post_new'),
    url(r'^quran-class-posts/(?P<pk>\d+)/$', QuranPostDetailView.as_view(),name='quran_post_detail'),
    url(r'^quran-class-posts/(?P<pk>\d+)/comment/$', add_comment_to_quran_post,name='comment_quran_post'),
    url(r'^islamic-studies-class-posts/$', IslamicStudiesPostListView.as_view(),name='islamic_studies_post_list'),
    url(r'^islamic-studies-class-posts/create/$', IslamicStudiesCreatePostView.as_view(),name='islamic_studies_post_new'),
    url(r'^islamic-studies-class-posts/(?P<pk>\d+)/$', IslamicStudiesPostDetailView.as_view(),name='islamic_studies_post_detail'),
    url(r'^islamic-studies-class-posts/(?P<pk>\d+)/comment/$', add_comment_to_islamic_studies_post,name='comment_islamic_studies_post'),
    url(r'^quran-class-students/attendance/$', QuranSchoolWeeksView.as_view(),name='quran_school_weeks'),
    url(r'^quran-class-students/attendance/(?P<pk>\d+)/student-list/$', QuranAttendanceList.as_view(),name='quran_attendance_list'),
    url(r'^quran-class-students/attendance/student-list/(?P<student>[\w\.-]+)/(?P<pk>\d+)$', QuranAttendanceUpdate.as_view(),name='quran_attendance_update'),
    url(r'^quran-class/attendance/$', QuranAttendanceStudentView.as_view(),name='student_quran_attendance'),
    url(r'^quran-class/exam-results/$', QuranExamStudentView.as_view(),name='student_quran_exams'),
    url(r'^islamic-studies-class-students/attendance/$', IslamicStudiesSchoolWeeksView.as_view(),name='islamic_studies_school_weeks'),
    url(r'^islamic-studies-class-students/attendance/(?P<pk>\d+)/student-list/$', IslamicStudiesAttendanceList.as_view(),name='islamic_studies_attendance_list'),
    url(r'^islamic-studies-class-students/attendance/student-list/(?P<student>[\w\.-]+)/(?P<pk>\d+)$', IslamicStudiesAttendanceUpdate.as_view(),name='islamic_studies_attendance_update'),
    url(r'^islamic-studies-class/attendance/$', IslamicStudiesAttendanceStudentView.as_view(),name='student_islamic_studies_attendance'),
    url(r'^islamic-studies-class/exam-results/$', IslamicStudiesExamStudentView.as_view(),name='student_islamic_studies_exams'),

]

src/administrator/models.py
from django.db import models

# Create your models here.

src/templates/administrator/administrator_recentactivity.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
</head>
<body>

      <!-- Recent Activity -->
        <div class="box box-primary">
 

          <div class="box-header with-border text-center">
            <h3 class="box-title">Recent Activity</h3>
          </div>
            
        <div class="box-body">

        <div class="nav-tabs-custom">

            <ul class="nav nav-tabs">
              <li class="active"><a href="#islamicstudiesfeed" data-toggle="tab">Islamic Studies Classes</a></li>
              <li><a href="#quranfeed" data-toggle="tab">Quran Classes</a></li>
             </ul>

            <div class="tab-content">

              <div class="active tab-pane" id="islamicstudiesfeed">
              
              {% if recent_islamic_studies %}

                  <!-- The timeline -->
                <ul class="timeline timeline-inverse">
                  <!-- timeline time label -->
             
                  <!-- /.timeline-label -->
      {% for recent in recent_islamic_studies %}
                    
                {% if recent.title %}
                      
               
                  <!-- timeline item -->
                  <li>
                    <i class="fa fa-envelope bg-green"></i>

                    <div class="timeline-item">
                      <span class="time"><i class="fa fa-clock-o"></i>{{recent.posted_date}}</span>

                      <h3 class="timeline-header">
                      <b>
                            {% if recent.author.username == request.user.username %} 
                            You
                            {% else %}
                            {{recent.author.first_name}} {{recent.author.last_name}}
                            {% endif %}
                      </b> posted in the Islamic Studies {{recent.class_level}} class discussion</h3>

                      <div class="timeline-body">
                                {{recent.message|safe}}
                      </div>
                      <div class="timeline-footer">
                        <a class="btn btn-success btn-xs" href="{% url 'islamic_studies_post_detail' pk=recent.pk %}">View</a>
                        <a class="btn btn-danger btn-xs" href="{% url 'comment_islamic_studies_post' pk=recent.pk %}">Comment</a>
                      </div>
                    </div>
                  </li>
                  <!-- END timeline item -->

                {% endif %}

                  {% if recent.comment %}
                    
                        <!-- timeline item -->
                        <li>
                          <i class="fa fa-comments bg-blue"></i>

                          <div class="timeline-item">
                            <span class="time"><i class="fa fa-clock-o"></i> {{recent.posted_date}}</span>

                            <h3 class="timeline-header">
                            <b>
                            {% if recent.author.username == request.user.username %} 
                            You
                            {% else %}
                            {{recent.author.first_name}} {{recent.author.last_name}}
                            {% endif %}
                            </b> 
                            commented on {% if recent.post.author.username == request.user.username %} your
                            {% else %}
                            {{recent.post.author.first_name}} {{recent.post.author.last_name}}'s
                            {% endif %} post <br><br>(Islamic Studies {{recent.post.class_level}})</h3>

                            <div class="timeline-body">
                              {{recent.comment|safe}}
                            </div>

                            <div class="timeline-footer">
                              <a class="btn btn-primary btn-flat btn-xs" href="{% url 'islamic_studies_post_detail' pk=recent.post.pk %}">View comment</a>
                            </div>
                          </div>
                        </li>
                        <!-- END timeline item --> 

                  {% endif %}


                  {% if recent.exam_number %}

                         <li>
                          <i class="fa fa-book bg-yellow"></i>

                          <div class="timeline-item">
                            <span class="time"><i class="fa fa-clock-o"></i> {{recent.posted_date}}</span>

                            <h3 class="timeline-header">
                            <b>
                            Exam {{recent.exam_number}} 
                            </b> 
                            score posted for {{recent.student.first_name}} {{recent.student.last_name}} (Islamic Studies {{recent.class_level}}) </h3>


                            <div class="timeline-footer">
                              <a class="btn btn-warning btn-flat btn-xs" href="{% url 'student_islamic_studies_exams'  %}">View Score</a>
                            </div>
                          </div>
                        </li>
                  
                 {% endif %}


       {% endfor %}

                    <li>
                          <i class="fa fa-clock-o bg-gray"></i>
                        </li>
                  

                </ul>

            {% else %}

            No recent activity to show.

            {% endif %}


              </div>






              <!-- /.tab-pane -->
              <div class="tab-pane" id="quranfeed">

                {% if recent_quran %}
                  
          
                  <!-- The timeline -->
                <ul class="timeline timeline-inverse">
                  <!-- timeline time label -->
             
                  <!-- /.timeline-label -->
                  {% for recent in recent_quran %}
                    
                {% if recent.title %}
                      
               
                  <!-- timeline item -->
                  <li>
                    <i class="fa fa-envelope bg-green"></i>

                    <div class="timeline-item">
                      <span class="time"><i class="fa fa-clock-o"></i>{{recent.posted_date}}</span>

                      <h3 class="timeline-header">
                      <b>
                            {% if recent.author.username == request.user.username %} 
                            You
                            {% else %}
                            {{recent.author.first_name}} {{recent.author.last_name}}
                            {% endif %}
                      </b> posted in the Quran {{recent.class_level}} class discussion.</h3>

                      <div class="timeline-body">
                                {{recent.message|safe}}
                      </div>
                      <div class="timeline-footer">
                        <a class="btn btn-success btn-xs" href="{% url 'quran_post_detail' pk=recent.pk %}">View</a>
                        <a class="btn btn-danger btn-xs" href="{% url 'comment_quran_post' pk=recent.pk %}">Comment</a>
                      </div>
                    </div>
                  </li>
                  <!-- END timeline item -->

                {% endif %}

                  {% if recent.comment %}
                    
                        <!-- timeline item -->
                        <li>
                          <i class="fa fa-comments bg-blue"></i>

                          <div class="timeline-item">
                            <span class="time"><i class="fa fa-clock-o"></i> {{recent.posted_date}}</span>

                            <h3 class="timeline-header">
                            <b>
                            {% if recent.author.username == request.user.username %} 
                            You
                            {% else %}
                            {{recent.author.first_name}} {{recent.author.last_name}}
                            {% endif %}
                            </b> 
                            commented on {% if recent.post.author.username == request.user.username %} your
                            {% else %}
                            {{recent.post.author.first_name}} {{recent.post.author.last_name}}'s
                            {% endif %} post <br><br> (Quran {{recent.post.class_level}})</h3>

                            <div class="timeline-body">
                              {{recent.comment|safe}}
                            </div>

                            <div class="timeline-footer">
                              <a class="btn btn-primary btn-flat btn-xs" href="{% url 'quran_post_detail' pk=recent.post.pk %}">View comment</a>
                            </div>
                          </div>
                        </li>
                        <!-- END timeline item --> 

                {% endif %}

                {% if recent.exam_number %}

                         <li>
                          <i class="fa fa-book bg-yellow"></i>

                          <div class="timeline-item">
                            <span class="time"><i class="fa fa-clock-o"></i> {{recent.posted_date}}</span>

                            <h3 class="timeline-header">
                            <b>
                            Exam {{recent.exam_number}}
                            </b> 
                            score posted for {{recent.student.first_name}} {{recent.student.last_name}} (Quran {{recent.class_level}})</h3>


                            <div class="timeline-footer">
                              <a class="btn btn-warning btn-flat btn-xs" href="{% url 'student_quran_exams' %}">View Score</a>
                            </div>
                          </div>
                        </li>
                  
                {% endif %}



              {% endfor %}

                     <li>
                          <i class="fa fa-clock-o bg-gray"></i>
                     </li>

                </ul>

                {% else %}

                No recent activity to show.

          {% endif %}


              </div>

            </div>
            <!-- /.tab-content -->
          </div>
          <!-- /.nav-tabs-custom -->
       
          












          </div>
          
          
          </div>









</body>
</html>

src/templates/administrator/islamicstudiesclassesattendancelist.html
{% extends "dashboardbase.html" %}

{% block title %}
<div class="text-center">
    <h2>
    Islamic Studies Attendance
  </h2>
</div>

{% endblock  %}

{% block maincontent %}
    <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Class Level</th>
                  <th>Attendance</th>
                </tr>
                </thead>
                <tbody>

                {% for class in islamic_studies_classes  %}
                  <tr>
                  <td>Islamic Studies {{class}}</td>             
                  <td><a href="{% url 'administrator:islamic_studies_weeks_list' level=class %}" class="btn btn-primary">View</a></td> </tr>
                  
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock  %}

src/templates/administrator/islamicstudiesclassesexamlist.html
{% extends "dashboardbase.html" %}

{% block title %}
<div class="text-center">
    <h2>
    Islamic Studies Classes
  </h2>
</div>

{% endblock  %}

{% block maincontent %}

    <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Class Level</th>
                  <th>Exam Scores</th>
                </tr>
                </thead>
                <tbody>

                {% for class in islamic_studies_classes  %}
                  <tr>
                  <td>Islamic Studies {{class}}</td>             
                  <td><a href="{% url 'administrator:islamic_studies_class_exam_scores' level=class %}" class="btn btn-primary">View</a></td> </tr>
                  
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock  %}

src/templates/administrator/islamicstudiesclassexamscores.html
{% extends "dashboardbase.html" %}

{% block title %}
<div class="text-center">
    <h2>
    Islamic Studies {{class_level}} Exam Scores
  </h2>
</div>

{% endblock  %}

{% block maincontent %}


{% if messages %}

  {% for message in messages %}

      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>

  {% endfor %}

{% endif %}

    <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Post Score</th>
                  <th>Exam 1</th>            
                  <th>Exam 2</th>   
                  <th>Exam 3</th>
                </tr>
                </thead>
                <tbody>

                {% for user in object_list  %}
                  <tr>
                    <td>{{user.first_name}}</td>
                    <td>{{user.last_name}}</td>
                    <td> <a href="{% url 'administrator:islamic_studies_exam_score_add' level=class_level student=user.username %}" class="btn btn-danger">Click Here</a> </td>
                    {% for exam in user.islamic_studies_exam_scores.all %}
                      <td>{{exam.exam_score}}</td>
                    {% endfor %}
                  </tr>
                  
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock  %}

src/templates/administrator/islamicstudiesrosterclasses.html
{% extends "dashboardbase.html" %}

{% block title %}
<div class="text-center">
    <h2>
    Islamic Studies Classes
  </h2>
</div>

{% endblock  %}

{% block maincontent %}
    <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Class Level</th>
                  <th>Class Roster</th>
                </tr>
                </thead>
                <tbody>

                {% for class in islamic_studies_classes  %}
                  <tr>
                  <td>Islamic Studies {{class}}</td>             
                  <td><a href="{% url 'administrator:islamicstudiesstudentlist' level=class %}" class="btn btn-primary">View</a></td> </tr>
                  
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock  %}

src/templates/administrator/islamicstuidesclassweekattendance.html
{% extends "dashboardbase.html" %}

{% block title %}


<div class="container-fluid">

<div class="text-center">
    <h2>
    Islamic Studies {{class_level}} Attendance: Week {{week_number}}
  </h2>
</div>

<div class="pull-right">
   <a href="{% url 'administrator:islamic_studies_attendance_list' %}" class="btn btn-primary">All Classes</a>
 </div>

</div>


{% endblock  %}

{% block maincontent %}
	

	  <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Attendance</th>  
                  <th>Update</th>          
                </tr>
                </thead>
                <tbody>
                {% for entry in object_list  %}
                	<tr>
                		<td>{{entry.student.first_name}}</td>
                		<td>{{entry.student.last_name}}</td>
                	  <td>{{entry.attendance}}</td>   
                    <td><a href="{% url 'administrator:islamic_studies_week_attendance_update' level=class_level week=week_number student=entry.student.username pk=entry.pk %}" class="btn btn-danger">Click Here</a></td>               
                	</tr>
                	
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->


{% endblock  %}

src/templates/administrator/quranclassweekattendance.html
{% extends "dashboardbase.html" %}

{% block title %}


<div class="container-fluid">

<div class="text-center">
    <h2>
    Quran {{class_level}} Attendance: Week {{week_number}}
  </h2>
</div>

<div class="pull-right">
   <a href="{% url 'administrator:quran_attendance_list' %}" class="btn btn-primary">All Classes</a>
 </div>

</div>


{% endblock  %}

{% block maincontent %}
	

	  <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Attendance</th> 
                  <th>Update</th>           
                </tr>
                </thead>
                <tbody>
                {% for entry in object_list  %}
                	<tr>
                		<td>{{entry.student.first_name}}</td>
                		<td>{{entry.student.last_name}}</td>
                	  <td>{{entry.attendance}}</td> 
                    <td><a href="{% url 'administrator:quran_week_attendance_update' level=class_level week=week_number student=entry.student.username pk=entry.pk %}" class="btn btn-danger">Click Here</a></td>               
                	</tr>
                	
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->


{% endblock  %}

src/templates/administrator/quranclassweekslist.html
{% extends "dashboardbase.html" %}

{% block title %}
<div class="text-center">
    <h2>
    Quran {{class_level}} Attendance
  </h2>
</div>

{% endblock  %}

{% block maincontent %}
    <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
                {% for teacher in teachers  %}
                  <b class="box-title">Teacher:</b> {{teacher.first_name}} {{teacher.last_name}}: {{teacher.email}}<br>
                {% endfor %}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Week</th>
                  <th>Date</th>
                  <th>Student Attendance</th>            
                </tr>
                </thead>
                <tbody>

                {% for week in object_list  %}
                  <tr>
                    <td>{{week.week_number}}</td>
                    <td>{{week.date}}</td>
                    <td><a href="{% url 'administrator:quran_week_attendance' level=class_level week=week.week_number %}" class="btn btn-primary">View</a></td>
                  </tr>
                  
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock  %}

src/templates/administrator/quranpostslist.html
{% extends "dashboardbase.html" %}

{% block title %}
<div class="text-center">
    <h2>
    Quran Classes
  </h2>
</div>

{% endblock  %}

{% block maincontent %}
    <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Class Level</th>
                  <th>Class Discussion</th>
                </tr>
                </thead>
                <tbody>

                {% for class in quran_classes  %}
                  <tr>
                  <td>Quran {{class}}</td>             
                  <td><a href="{% url 'administrator:quranclassposts' level=class %}" class="btn btn-primary">View</a></td> </tr>
                  
                {% endfor %}
                
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock  %}